version: "3.9"

services:
  web-test:
    build:
      context: ./spike-app
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
    volumes:
      - ./spike-app:/app:cached
      - go-mod-cache:/go/pkg/mod
    stdin_open: true
    tty: true

volumes:
  go-mod-cache:
