services:
  web-prod:
    depends_on:
      - db-prod
    build:
      context: .
      target: prod
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=production
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_prod

  # 開発環境
  web-dev:
    depends_on:
      - db-dev
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./spike-app:/spike-app
    environment:
      - PORT=8000
      - ENV=development
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_dev

  # 開発用DB
  db-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_dev
    ports:
      - "5200:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  # 本番用DB
  db-prod:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_prod
    ports:
      - "5432:5432"
    volumes:
      - db-prod-data:/var/lib/postgresql/data

  # GCP SDK
  gcloud:
    image: google/cloud-sdk:latest
    stdin_open: true
    tty: true
    working_dir: /spike-app
    volumes:
      - .:/spike-app
      - ./.gcloud-config:/root/.config/gcloud

  # cloud sql proxy
  cloud-sql:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    volumes:
      - ./.spike-app-db-client-credential.json:/config
    ports:
      - "5432:5432"
    command: /cloud_sql_proxy -instances=spike-backend-gin:asia-northeast1:spike-app=tcp:0.0.0.0:5432 -credential_file=/config

  # 本番環境接続用シェル
  prod-shell:
    depends_on:
      - cloud-sql
    build:
      context: .
      target: prod
    init: true
    stdin_open: true
    tty: true
    volumes:
      - .:/spike-app
    environment:
      - ENV=production
      - POSTGRES_USER=${PROD_DB_USER}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
      - POSTGRES_DB=${PROD_DB_NAME}
      - DATABASE_URL=postgresql+pg8000://postgres:${PROD_DB_PASSWORD}@cloud-sql:5432/spike_prod

volumes:
  db-dev-data:
  db-prod-data:
