services:
  web:
    build:
      context: .
      target: prod
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PORT=8080

  # 開発環境
  dev:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    working_dir: /app/spike-app
    volumes:
      - .:/app

  # GCP SDK
  gcloud:
    image: google/cloud-sdk:latest
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - ./.gcloud-config:/root/.config/gcloud
