version: "3.9"

services:
  web-test:
    # depends_on:
    #   - db-test
    build:
      context: ./spike-app
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/spike-app
    stdin_open: true
    tty: true

  # テスト用 DB サーバー
  # db-test:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=spike-seed_test
  #   volumes:
  #     - db-test_data:/var/lib/postgresql/data
  #   command: -p 5433
