services:
  web-prod:
    depends_on:
      - db-prod
    build:
      context: .
      target: prod
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=production
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_prod

  # 開発環境
  web-dev:
    depends_on:
      - db-dev
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./spike-app:/spike-app
    environment:
      - PORT=8000
      - ENV=development
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_dev

  # 開発用DB
  db-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_dev
    ports:
      - "5200:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  # 本番用DB
  db-prod:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=spike
      - POSTGRES_PASSWORD=spike
      - POSTGRES_DB=spike_prod
    ports:
      - "5432:5432"
    volumes:
      - db-prod-data:/var/lib/postgresql/data

  # GCP SDK
  gcloud:
    image: google/cloud-sdk:latest
    stdin_open: true
    tty: true
    working_dir: /spike-app
    volumes:
      - .:/spike-app
      - ./.gcloud-config:/root/.config/gcloud

volumes:
  db-dev-data:
  db-prod-data:
